# Name of the GitHub Actions workflow.
name: Build and Merge Firmware

# This workflow is triggered automatically when a new Release is created
# or can be run manually from the Actions tab.
on:
  release:
    types: [created]
  workflow_dispatch:

# Environment variables for easy configuration.
env:
  # The folder name for your sketch. MUST NOT contain the .ino extension.
  SKETCH_FOLDER: ESPTimeCast_ESP32
  
  # FQBN for your Adafruit board.
  BOARD_FQBN: esp32:esp32:adafruit_feather_esp32s3
  
  # Configuration for merged binary
  ESP_CHIP_TYPE: esp32s3
  ADDR_BOOTLOADER: "0x1000"
  ADDR_PARTITIONS: "0x8000"
  ADDR_FIRMWARE: "0x10000"
  ADDR_LITTLEFS: "0x210000"
  LITTLEFS_PARTITION_SIZE: 1572864

# A workflow is made up of one or more jobs.
jobs:
  build:
    # The type of virtual machine to run the job on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install Libraries
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "MD_Parola"
          arduino-cli lib install "MD_MAX72xx"
          arduino-cli lib install "AsyncTCP"
          arduino-cli lib install "ESPAsyncWebServer"

      - name: Install ESP32 Platform
        run: arduino-cli core install esp32:esp32@2.0.17

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn ${{ env.BOARD_FQBN }} --output-dir build_output ./${{ env.SKETCH_FOLDER }}

      - name: Build LittleFS Filesystem Image
        run: |
          # Find the mklittlefs tool path dynamically, ensuring it's a file
          MK_TOOL_PATH=$(find ~/.arduino15/packages/esp32/tools/mklittlefs -type f -name "mklittlefs" | head -n 1)
          # Run the tool using its full path
          $MK_TOOL_PATH -c data -b 4096 -p 256 -s ${{ env.LITTLEFS_PARTITION_SIZE }} littlefs.bin
      
      - name: Rename Firmware File for Clarity
        run: mv build_output/${{ env.SKETCH_FOLDER }}.bin build_output/firmware.bin

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install esptool
        run: pip install esptool

      - name: Merge Binaries
        run: |
          esptool.py --chip ${{ env.ESP_CHIP_TYPE }} merge_bin -o merged-firmware.bin \
          ${{ env.ADDR_BOOTLOADER }} build_output/bootloader.bin \
          ${{ env.ADDR_PARTITIONS }} build_output/partitions.bin \
          ${{ env.ADDR_FIRMWARE }} build_output/firmware.bin \
          ${{ env.ADDR_LITTLEFS }} littlefs.bin

      - name: Upload Merged Firmware to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./merged-firmware.bin
          asset_name: merged-firmware.bin
          asset_content_type: application/octet-stream